const COUNTRY_CODES: Record<string, string> = {
  // América do Norte e Central
  'United States': 'us',
  USA: 'us',
  Mexico: 'mx',
  Canada: 'ca',
  Panama: 'pa',
  Honduras: 'hn',
  Jamaica: 'jm',
  'El Salvador': 'sv',
  'Trinidad and Tobago': 'tt',
  'Costa Rica': 'cr',
  Guatemala: 'gt',
  Cuba: 'cu',
  Haiti: 'ht',
  'Curaçao': 'cw',
  // América do Sul
  Brazil: 'br',
  Argentina: 'ar',
  Colombia: 'co',
  Ecuador: 'ec',
  Uruguay: 'uy',
  Venezuela: 've',
  Peru: 'pe',
  Bolivia: 'bo',
  Chile: 'cl',
  Paraguay: 'py',
  // Europa
  Germany: 'de',
  France: 'fr',
  England: 'gb-eng',
  Spain: 'es',
  Italy: 'it',
  Portugal: 'pt',
  Netherlands: 'nl',
  Belgium: 'be',
  Switzerland: 'ch',
  Croatia: 'hr',
  Serbia: 'rs',
  Austria: 'at',
  Denmark: 'dk',
  Scotland: 'gb-sct',
  Hungary: 'hu',
  Slovakia: 'sk',
  Albania: 'al',
  Slovenia: 'si',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Poland: 'pl',
  Romania: 'ro',
  Ukraine: 'ua',
  Turkey: 'tr',
  'Türkiye': 'tr',
  Greece: 'gr',
  Norway: 'no',
  Sweden: 'se',
  Wales: 'gb-wls',
  'North Macedonia': 'mk',
  Montenegro: 'me',
  'Bosnia and Herzegovina': 'ba',
  Bosnia: 'ba',
  Finland: 'fi',
  Iceland: 'is',
  Ireland: 'ie',
  // África
  'Cabo Verde': 'cv',
  Morocco: 'ma',
  Senegal: 'sn',
  Egypt: 'eg',
  Nigeria: 'ng',
  Cameroon: 'cm',
  Ghana: 'gh',
  'Ivory Coast': 'ci',
  "Cote d'Ivoire": 'ci',
  "Côte d'Ivoire": 'ci',
  'DR Congo': 'cd',
  'Congo DR': 'cd',
  'South Africa': 'za',
  Tunisia: 'tn',
  Algeria: 'dz',
  Mali: 'ml',
  Zambia: 'zm',
  Tanzania: 'tz',
  Comoros: 'km',
  Benin: 'bj',
  Angola: 'ao',
  // Ásia
  Japan: 'jp',
  'South Korea': 'kr',
  'Korea Republic': 'kr',
  'North Korea': 'kp',
  Iran: 'ir',
  'IR Iran': 'ir',
  'Saudi Arabia': 'sa',
  Australia: 'au',
  Qatar: 'qa',
  Iraq: 'iq',
  Jordan: 'jo',
  Uzbekistan: 'uz',
  Oman: 'om',
  'United Arab Emirates': 'ae',
  UAE: 'ae',
  Bahrain: 'bh',
  China: 'cn',
  Indonesia: 'id',
  // Oceania
  'New Zealand': 'nz',
}

export function getFlagUrl(teamName: string): string {
  const code = COUNTRY_CODES[teamName]
  if (!code) return ''
  return `https://flagcdn.com/w40/${code}.png`
}
