export const FLAG_MAP: Record<string, string> = {
  // Americas
  Brazil: '🇧🇷',
  Argentina: '🇦🇷',
  Colombia: '🇨🇴',
  Ecuador: '🇪🇨',
  Uruguay: '🇺🇾',
  Venezuela: '🇻🇪',
  Peru: '🇵🇪',
  Bolivia: '🇧🇴',
  Chile: '🇨🇱',
  Paraguay: '🇵🇾',
  'United States': '🇺🇸',
  USA: '🇺🇸',
  Canada: '🇨🇦',
  Mexico: '🇲🇽',
  Panama: '🇵🇦',
  'Costa Rica': '🇨🇷',
  Honduras: '🇭🇳',
  Jamaica: '🇯🇲',
  'El Salvador': '🇸🇻',
  'Trinidad and Tobago': '🇹🇹',
  Guatemala: '🇬🇹',
  // Europe
  Germany: '🇩🇪',
  France: '🇫🇷',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Spain: '🇪🇸',
  Italy: '🇮🇹',
  Portugal: '🇵🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Switzerland: '🇨🇭',
  Croatia: '🇭🇷',
  Serbia: '🇷🇸',
  Austria: '🇦🇹',
  Denmark: '🇩🇰',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Hungary: '🇭🇺',
  Slovakia: '🇸🇰',
  Albania: '🇦🇱',
  Slovenia: '🇸🇮',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  Poland: '🇵🇱',
  Romania: '🇷🇴',
  Ukraine: '🇺🇦',
  Turkey: '🇹🇷',
  Greece: '🇬🇷',
  Norway: '🇳🇴',
  Sweden: '🇸🇪',
  Wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'North Macedonia': '🇲🇰',
  Montenegro: '🇲🇪',
  Bosnia: '🇧🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  Finland: '🇫🇮',
  Iceland: '🇮🇸',
  Ireland: '🇮🇪',
  // Africa
  Morocco: '🇲🇦',
  Senegal: '🇸🇳',
  Egypt: '🇪🇬',
  Nigeria: '🇳🇬',
  Cameroon: '🇨🇲',
  Ghana: '🇬🇭',
  'Ivory Coast': "🇨🇮",
  "Cote d'Ivoire": '🇨🇮',
  'DR Congo': '🇨🇩',
  'Congo DR': '🇨🇩',
  'South Africa': '🇿🇦',
  Tunisia: '🇹🇳',
  Algeria: '🇩🇿',
  Mali: '🇲🇱',
  Zambia: '🇿🇲',
  Tanzania: '🇹🇿',
  Comoros: '🇰🇲',
  Benin: '🇧🇯',
  Angola: '🇦🇴',
  // Asia
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Korea: '🇰🇷',
  'Korea Republic': '🇰🇷',
  'North Korea': '🇰🇵',
  Iran: '🇮🇷',
  'IR Iran': '🇮🇷',
  'Saudi Arabia': '🇸🇦',
  Australia: '🇦🇺',
  Qatar: '🇶🇦',
  Iraq: '🇮🇶',
  Jordan: '🇯🇴',
  Uzbekistan: '🇺🇿',
  Oman: '🇴🇲',
  'United Arab Emirates': '🇦🇪',
  UAE: '🇦🇪',
  Bahrain: '🇧🇭',
  China: '🇨🇳',
  Indonesia: '🇮🇩',
  // Oceania
  'New Zealand': '🇳🇿',
}

export function getFlag(teamName: string): string {
  return FLAG_MAP[teamName] ?? '🏳️'
}
