const TEAM_NAMES_PTBR: Record<string, string> = {
  // América do Norte e Central
  'United States': 'Estados Unidos',
  USA: 'Estados Unidos',
  Mexico: 'México',
  Canada: 'Canadá',
  Panama: 'Panamá',
  Honduras: 'Honduras',
  Jamaica: 'Jamaica',
  'El Salvador': 'El Salvador',
  'Trinidad and Tobago': 'Trinidad e Tobago',
  'Costa Rica': 'Costa Rica',
  Guatemala: 'Guatemala',
  Cuba: 'Cuba',
  Haiti: 'Haiti',
  'Curaçao': 'Curaçao',
  // América do Sul
  Brazil: 'Brasil',
  Argentina: 'Argentina',
  Colombia: 'Colômbia',
  Ecuador: 'Equador',
  Uruguay: 'Uruguai',
  Venezuela: 'Venezuela',
  Peru: 'Peru',
  Bolivia: 'Bolívia',
  Chile: 'Chile',
  Paraguay: 'Paraguai',
  // Europa
  Germany: 'Alemanha',
  France: 'França',
  England: 'Inglaterra',
  Spain: 'Espanha',
  Italy: 'Itália',
  Portugal: 'Portugal',
  Netherlands: 'Holanda',
  Belgium: 'Bélgica',
  Switzerland: 'Suíça',
  Croatia: 'Croácia',
  Serbia: 'Sérvia',
  Austria: 'Áustria',
  Denmark: 'Dinamarca',
  Scotland: 'Escócia',
  Hungary: 'Hungria',
  Slovakia: 'Eslováquia',
  Albania: 'Albânia',
  Slovenia: 'Eslovênia',
  'Czech Republic': 'República Tcheca',
  Czechia: 'República Tcheca',
  Poland: 'Polônia',
  Romania: 'Romênia',
  Ukraine: 'Ucrânia',
  Turkey: 'Turquia',
  'Türkiye': 'Turquia',
  Greece: 'Grécia',
  Norway: 'Noruega',
  Sweden: 'Suécia',
  Wales: 'País de Gales',
  'North Macedonia': 'Macedônia do Norte',
  Montenegro: 'Montenegro',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  Bosnia: 'Bósnia',
  Finland: 'Finlândia',
  Iceland: 'Islândia',
  Ireland: 'Irlanda',
  // África
  'Cabo Verde': 'Cabo Verde',
  Morocco: 'Marrocos',
  Senegal: 'Senegal',
  Egypt: 'Egito',
  Nigeria: 'Nigéria',
  Cameroon: 'Camarões',
  Ghana: 'Gana',
  'Ivory Coast': 'Costa do Marfim',
  "Cote d'Ivoire": 'Costa do Marfim',
  "Côte d'Ivoire": 'Costa do Marfim',
  'DR Congo': 'RD Congo',
  'Congo DR': 'RD Congo',
  'South Africa': 'África do Sul',
  Tunisia: 'Tunísia',
  Algeria: 'Argélia',
  Mali: 'Mali',
  Zambia: 'Zâmbia',
  Tanzania: 'Tanzânia',
  Comoros: 'Comores',
  Benin: 'Benim',
  Angola: 'Angola',
  // Ásia
  Japan: 'Japão',
  'South Korea': 'Coreia do Sul',
  'Korea Republic': 'Coreia do Sul',
  'North Korea': 'Coreia do Norte',
  Iran: 'Irã',
  'IR Iran': 'Irã',
  'Saudi Arabia': 'Arábia Saudita',
  Australia: 'Austrália',
  Qatar: 'Catar',
  Iraq: 'Iraque',
  Jordan: 'Jordânia',
  Uzbekistan: 'Uzbequistão',
  Oman: 'Omã',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  UAE: 'Emirados Árabes Unidos',
  Bahrain: 'Bahrein',
  China: 'China',
  Indonesia: 'Indonésia',
  // Oceania
  'New Zealand': 'Nova Zelândia',
}

export function getTeamNamePTBR(name: string): string {
  return TEAM_NAMES_PTBR[name] ?? name
}
